language: go

after_success: docker build -t norsknettarkiv/veidemann-reset:${TRAVIS_BRANCH} .

before_deploy: echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  provider: script
  script: docker push norsknettarkiv/veidemann-reset:${TRAVIS_BRANCH}
  on:
    tags: true

after_deploy: docker logout

env:
  global:
  - secure: nots1NdaiDcg3BCrXu+BFiH6elvwK/lM6XuLIow1xUwshjAzp0xSI0QQBy1QsacO1w/o3aZmozk9TvXdYuELJglh5kZWdqNccUr9XroUsgD5reeYxFLs87WvsLPW6m5fHKTcL+e0mhO9kHHry4v0a/RoK2hUQcK8bBqSzzP5uxdPGMtkZ7vzSppYCBNqpjjubReRS1thkY+WAsOUSxJSFbVDPHs8PQmnhVP9pKO7c0t70SF5NwzncStAqJWRTzrv1ddcqSqr3pgmCV7XYLIoH84GUKydywSItC24mmnx7kjIJ+Rfy6Irio/qRzPCbWb7mReoKp6hBQ9I7S5BzsO5SX/iDgUPt07Ivvn+r2o8Ejhc4V8//hrgqYPEQqH8ilNhBESEwhe6eE0GhcZiC4z665lTZFPagU/nc8FVOqnprxgbiuJACJex4n9xRhWaoB/O8a9LHCWkDSHTyrfT1hY0AZuUrmVjnCRffWaswHuLTMQwwE1QLSAUsmSya/wZRrLzKbsogRuXJ7A38VllPnyAazprpuGTzohD/kQ+VavcYdzCF4XDSJ53Evlom9LPlKDAutbleh0NO7aEg9oLQUvKwu97MMKrGqYSLPPGIIwBac9P+14aTGhmT/gLEASvoX3F0SxiX3ZobXNRsEyLC/xv3b9JEJYQde5vGe8V6wvqPTQ=
  - secure: dxjl61sSIUP3zozmYScl0PO8MHEfE4O7AStyCia9Dr2O50yHYEZ22WsesdIinF05x5ojJ6WuN608aLPTmT1yTbNS1AE4vOsvgMZwW5lXtIBM4WOkg0RpPM8tn/gUGgBIhbB1dhkpoUH++LO75ygB9QIObRrC2b0tOA32/l+yd2M4lnaYaHpBa54d+6eve5ue8AEK0v2WbuqzSy3zjcU2CdNCy6RHERAATJQIs2cZXPmmxswum3sfeOYW7WHGuZ+xXsY5SdvSggERCqeqdtOetNZUt8LSAi6c7lyKMbeJpXC/XWu/pQvu8hCQU8yyTgJIj35xEGHRIOm++VRBdwzIC58FAghHed51NcH24XzS7W5yIDOQdF3l+8mXehe1UiqxUbSyXBh6uPwMJpIezaaDYcjkDyHvovQWbJURQMp4WFWbuNWvn+m1grnqv+55n8XDGCQeCWZ/fgnZCUzfpavgXCuYt58QwJ5wwbdgi9K53JNKRmtEXUtTyZMm+AvXD1Cg8ux/K3T9DDBewvDjXTnKd6UpTve9lhjYkLLizJXfQoEG1spWaQceyxBci8B46q0aPyiv2qADpal/X2ax0ByRe0M+wz98CAt+9KNJD5qlNjo6tPkWz3of34GuQt3saIV9HkpLThKDhqiCWfhIR0ePSKI3PFrHFE3Jdwe8XTC1vq0=
