kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: veidemann

resources:
  - job.yaml

configMapGenerator:
  - name: veidemann-reset-env
    literals:
      - RETHINKDB_HOST=rethinkdb-proxy
      - REDIS_HOST=redis-master
      - SCYLLA_HOSTS=scylla-client
      - SCYLLA_KEYSPACE=v7n_v3_dev
