kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: veidemann

commonLabels:
  app.kubernetes.io/name: veidemann-reset

resources:
  - job.yaml

configMapGenerator:
  - name: veidemann-reset-env
    literals:
      - RETHINKDB_HOST=rethinkdb-proxy
